PackageIdentifier: Microsoft.TeamsContinuousDeployment
PackageName: Microsoft Teams Continuous Deployment
Moniker: teams-continuous-deployment
PackageVersion: 1.4.00.11361
Publisher: Microsoft Corporation
Author: Microsoft Corporation
License: (c) 2021 Microsoft Corporation
LicenseUrl: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default
ShortDescription: Meet, chat, call, and collaborate in just one place.
PackageUrl: https://www.microsoft.com/en-us/microsoft-teams/group-chat-software
Installers:
- Architecture: x64
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.11361/Teams_windows_x64.exe
  InstallerSha256: 914f4e194e320b5d237dd7769ce68ccc840ec8f6f224ee0beb71d7510a17652b
  InstallerType: exe
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
