PackageIdentifier: Microsoft.TeamsContinuousDeployment
PackageName: Microsoft Teams Continuous Deployment
Moniker: teams-continuous-deployment
PackageVersion: 1.4.00.11463
Publisher: Microsoft Corporation
Author: Microsoft Corporation
License: (c) 2021 Microsoft Corporation
LicenseUrl: https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default
ShortDescription: Meet, chat, call, and collaborate in just one place.
PackageUrl: https://www.microsoft.com/en-us/microsoft-teams/group-chat-software
Installers:
- Architecture: x64
  InstallerUrl: https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.11463/Teams_windows_x64.exe
  InstallerSha256: ff6dd3784ec3ee1934617080104706d103de271f4d1cc754ba7611fa2b684d61
  InstallerType: exe
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
